name: CD - Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: theitamarshalev/backend_guide:latest
  CONTAINER_NAME: backend_guide
  TARGET_BRANCH: main

jobs:
  wait:
    name: Wait for All CI workflows
    uses: ./.github/workflows/wait-for-workflows.yaml
    with:
      workflow_files: |
        ci-backend.yaml
        ci-docker.yaml

  build:
    name: Build
    if: needs.wait.outputs.all_passed == 'true'
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_REPO }} .

      - name: Push Docker image to remote registry
        run: docker push ${{ env.DOCKER_REPO }}

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: ${{ secrets.USERNAME_SERVER }}
          host: ${{ secrets.HOST_SERVER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
            docker rm -f ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
            docker pull ${{ env.DOCKER_REPO }}
            docker run -d --restart always -p 8000:8000 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_REPO }}
